### PR TITLE
Nikon Z 30 support

### PR DESCRIPTION
**Pull request by kmilos**
From https://github.com/darktable-org/darktable/issues/12239

Forgot about it, too bad it slipped through the cracks for dt 4.2 🤦

### CODE REVIEW

**Comment by LebedevRI** [comment]
> Forgot about it, too bad it slipped through the cracks for dt 4.2

Hm, why is there a tag already? I was told 22'th.

**Comment by LebedevRI** [comment]
@kmilos thank you!
If you want some pointers, things like [this](https://github.com/darktable-org/rawspeed/blob/develop/src/librawspeed/decoders/ArwDecoder.cpp#L70-L73) are prime candidates
for refactoring -- there should be some Entries in that TIFF that provide
the same data, we shouldn't hardcode it.
Same for anything that is driven by `hints.has("<???>")`.

**Comment by kmilos** [comment]
> Hm, why is there a tag already? I was told 22'th.

Yeah, that's including the binary packaging for Windows and macOS, so AFAIK there's always a couple of days of buffer to allow those volunteers to do their work and some last minute testing... Pascal usually sends an email just before the freeze...

**Comment by kmilos** [comment]
Can't promise, but I might look into those pointers if I find the time. Thanks!

**Pull request merged**
