### PR TITLE
Add Ricoh GR III

### PR DESCRIPTION
**Pull request by johnny-bit**
I hope I made this one right.

This allows for full run of https://github.com/darktable-org/darktable/issues/9091 (which reads from cameras.xml) as well as makes darktable nicely accept DNG from https://raw.pixls.us/getfile.php/3115/nice/Ricoh%20-%20RICOH%20GR%20III%20-%2014bit%20(3:2).DNG with no rendition artifacts

(without this, the colors i get are wack).

### CODE REVIEW

**Comment by johnny-bit** [comment]
garbage bot...

**Comment by grattus** [comment]
Thanks for taking the time. Ricoh GR Digital 3 and Ricoh GR III are different cameras so you may want to change your commit to `<ID make="Ricoh" model="GR III">Ricoh GR III</ID>` for greater clarity?

**Comment by johnny-bit** [comment]
Sure.

btw: congrats ricoh! "Ricoh GR III digital " != "Ricoh GR Digital 3". one was released in 2019, other in 2009... No confusing names what so ever :)

**Review by LebedevRI — COMMENTED** [review]
Well, we really shouldn't second-guess DNG's, but then this is consistent with the rest of this file, so whatever.

**Comment by LebedevRI** [comment]
I don't think any of these Ricoh entries are right, but well...

**Pull request merged**
