### PR TITLE
Fixing FixBadPixelsList for DNG RawImageDataFloat images

### PR DESCRIPTION
**Pull request by jenshannoschwalm**
There have been discussions about HDRmerged images showing strange artefacts, that are difficult to explain just by applying a wrong FixBadPixelsList.

See darktable-org/darktable#3510 and  jcelaya/hdrmerge#197

Instead of my first assumption this seems to originate from a wrong RawImageDataFloat::fixBadPixel

@heckflosse , @KristijanZic

### CODE REVIEW

**Comment by LebedevRI** [comment]
I agree that this seems to be the proper fix, but then it matches the `uint16_t` implementation,
which highlights why these bugs are here - code duplication.
https://github.com/darktable-org/rawspeed/blob/198952f61c28f7bf4496e5bde2ffddcbf2363a6d/src/librawspeed/common/RawImageDataU16.cpp#L376-L471

Can you rebase this to not include the dng commit? I'd merge this then.

**Comment by jenshannoschwalm** [comment]
I haven't rebased anything yet, could you explain in short?

**Comment by heckflosse** [comment]
About badpixel interpolation (on raw data) maybe have a look at the rt code

for bayer:
https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/badpixels.cc#L66

for xtrans:
https://github.com/Beep6581/RawTherapee/blob/dev/rtengine/badpixels.cc#L288

Both are also well documented in code (which I usually do not)

**Comment by LebedevRI** [comment]
Licenses are incompatible though

**Comment by fanckush** [comment]
@jenshannoschwalm So the issue is `RawImageDataFloat::fixBadPixel` and not HDRMerge? or was it simply both together? I guess what I'm trying to say: is HDRMerge still supposed to fix anything regarding BadPixels or is this sufficient?

**Comment by jenshannoschwalm** [comment]
@fanckush in fact it's two problems. One was the one fixed here resulting in those strange artefacts. **But** of course HDRMerge right now creates merged images with a simply wrong opcode list. It should do the opcode-list work for every image before merging to gain best quality but also must not use the opcode list of one image for the merged one. So some homework for you to be done :-) Most people will not recognize the remaining problem on your side yet ...

**Comment by LebedevRI** [comment]
> Licenses are incompatible though

Are you saying that it is okay to copy-paste gpl3 code into lgpl3 library?

**Pull request merged**
