### PR TITLE
Olympus E-P7 support

### PR DESCRIPTION
**Pull request by kmilos**
Addresses https://github.com/darktable-org/darktable/issues/11810

The no crop seems ok to me...

### CODE REVIEW

**Comment by LebedevRI** [comment]
RPU sample still missing.

**Comment by kmilos** [comment]
Hm, the original issue said "submitted", it's not in the upload backlog somewhere?

**Comment by LebedevRI** [comment]
There is nothing for `Olympus PEN EP-7`, but there is one for `OLYMPUS CORPORATION E-P7`. If that is it then it is there.

**Comment by kmilos** [comment]
Yep, that's the one that matches this PR:

`<Camera make="OLYMPUS CORPORATION" model="E-P7">`

**Comment by LebedevRI** [comment]
@kmilos thank you!

**Pull request merged**
