### PR TITLE
Renamed option BUILD_TESTING to BUILD_RS_TESTING

### PR DESCRIPTION
**Pull request by burrima**
Necessary since it conflicts with internal cmake/ctest mechanisms (see
https://cmake.org/cmake/help/latest/command/enable_testing.html).

Thank you @cryptomilk for pointing this out!

Signed-off-by: Martin Burri <info@burrima.ch>

### CODE REVIEW

**Review by LebedevRI — CHANGES_REQUESTED** [review]
Please can you explain _how_ it conflicts?
The option is named as such precisely because there is `BUILD_TESTING` option.

**Comment by burrima** [comment]
Related to this pull request in darktable: https://github.com/darktable-org/darktable/pull/4154
The statement from @cryptomilk was that rawspeed is setting the option BUILD_TESTING to Off which would disable it globally in darktable.

**Comment by LebedevRI** [comment]
Setting it *where*?

**Comment by burrima** [comment]
Ok, I will talk to @cryptomilk first when he is back from the devconf.cz - I understand too little of cmake to give you a good explanation. Please stay tuned.

**Comment by cryptomilk** [comment]
You can close this, it is a non-issue :-)

**Comment by LebedevRI** [comment]
As discussed in https://github.com/darktable-org/darktable/pull/4154#issuecomment-578499077

**Pull request closed without merging**
