### PR TITLE
Add support for Fujifilm X-H2 and X-H2S

### PR DESCRIPTION
**Pull request by Sturmflut**
Created using files from the sample galleries at https://www.dpreview.com/samples/6493635762/fujifilm-x-h2s-sample-gallery-dpreview-tv and https://www.photographyblog.com/previews/fujifilm_x_h2_photos . Tested with darktable.

### CODE REVIEW

**Comment by kmilos** [comment]
See also https://github.com/darktable-org/rawspeed/issues/374

I doubt the H2 color matrix is the same as the H2S one as the sensors are different - better wait until it's in production and Adobe DNG Converter support is available, and revisit the PR.

**Comment by etrigan63** [comment]
Files from Production X-H2 have been uploaded (see https://github.com/darktable-org/darktable/issues/12584). Also, the previous code for the X-H2S stopped working with the 4.0.1 update to dt. Raw files present as blank screens.

**Comment by etrigan63** [comment]
I have uploaded new raw samples for the X-H2S. With the proposed changes to cameras.xml I was able to open the lossless compressed and uncompressed images, but the compressed image gave me a white balance error. This may be due to a firmware update on Fuji's part for the X-H2S.

**Comment by mwperina** [comment]
After upgrade to Darktable 4.0.1 I can import uncompressed RAF from X-H2S (firmware 2.00) without any problem and after working on more than 50 photos I haven't found any obvious issue, images are processed fine. So is there anything blocking us from getting X-H2S support merged?

**Review by mwperina — APPROVED** [review]
X-H2S part works for me fine

**Comment by kmilos** [comment]
The X-H2 samples are now published on RPU, and ADC 15 w/ support for this camera is now out as well - I was able to confirm the black/white levels and the color matrix as in the PR. 👍

**Comment by LebedevRI** [comment]
The crop is very obviously wrong here.

**Comment by etrigan63** [comment]
I have to agree. I never noticed before because my dt is dark and I did not see the black edge. I also tend to lens correct and that removes the edge.

**Comment by LebedevRI** [comment]
@Sturmflut @kmilos @etrigan63 thank you!

**Pull request merged**
