### PR TITLE
VC5Decompressor: support GoPro HERO10 CFA pattern

### PR DESCRIPTION
**Pull request by kmilos**
Proposal for addressing https://github.com/darktable-org/darktable/issues/10072

### CODE REVIEW

**Comment by LebedevRI** [comment]
Thank you for confirming my suspicions, but that is not the fix i envision.

**Comment by kmilos** [comment]
Sure, just wanted to share the minimal working test...

**Comment by arbasel** [comment]
Given that this is closed, is there something that I can do so that my GoPro photos open correctly in Darktable?

**Comment by ghost** [comment]
@kmilos Is this not getting fixed for GoPro HERO10 RAW files?

**Pull request closed without merging**
