### PR TITLE
Sony ILCE-6700 support

### PR DESCRIPTION
**Pull request by kmilos**
Addresses https://github.com/darktable-org/rawspeed/issues/507

Confirmed w/ latest ADC 15.5 - crop and matrix are identical to FX30.

### CODE REVIEW

**Comment by LebedevRI** [comment]
Thank you!

Please note that `Addresses #<>` is not one of the spelling recognized by the github.

**Comment by kmilos** [comment]
> Please note that `Addresses #<>` is not one of the spelling recognized by the github.

That's right. I'm avoiding the automatic closing by "fixes" or "resolves" as instructed by you in the past as it messed w/ your project triage?

**Comment by LebedevRI** [comment]
I _think_ that was about closing issues in another repo (the dt's one), not in the same repo for which the commit is.

**Comment by kmilos** [comment]
Wasn't it also about the automatic closing also moving issues around automatically on the "New camera" project dashboard to "Done"?

Anyhow, happy to change the keyword if you think it is no longer necessary to avoid the automatic closing...

**Pull request merged**
