### PR TITLE
Nikon Z 8 support

### PR DESCRIPTION
**Pull request by kmilos**
Addresses https://github.com/darktable-org/darktable/issues/14593

NB: This is a stub for now, I have not verified the crop.

Used the latest ADC 15.3.1 which also added support for this camera a couple of days ago.

### CODE REVIEW

**Comment by kmilos** [comment]
@LViatour Can you please upload the full sample set so this can proceed?

**Comment by LViatour** [comment]
There are only three raw file formats on the Nikon Z8.

I can't send more than one raw image to the server.
Here is the download link via my server of the three Nikon Z8 raw files
http://luc.lucnix.be/Nikon-Z8-raw.zip

**Comment by kmilos** [comment]
Please upload one by one, with a note of compression mode used for each.

**Comment by LViatour** [comment]
here are the three formats are upload

**Comment by kmilos** [comment]
Thanks! @LebedevRI

**Comment by LebedevRI** [comment]
@LViatour thank you, verified!

**Comment by LebedevRI** [comment]
@kmilos @LViatour thank you!
I believe, the crop is correct here...

**Pull request merged**
