### PR TITLE
Add basic camera support for Sony ZV-1

### PR DESCRIPTION
**Pull request by philippnormann**
This PR adds basic camera support for the new [Sony ZV-1](https://www.sony.com/electronics/cyber-shot-compact-cameras/zv-1/specifications).

Someone already uploaded a sample `.ARW` file to https://raw.pixls.us/. I could provide more examples, if necessary.

I would also like to contribute a color matrix for this model, but since Adobe doesn't support this camera yet, I am not sure how to get ahold of it. 

@LebedevRI do you have any suggestions on how we might get the color matrix using another method?

### CODE REVIEW

**Comment by LebedevRI** [comment]
> I would also like to contribute a color matrix for this model, but since Adobe doesn't support this camera yet, I am not sure how to get ahold of it.

If this camera is just a rename of some other camera, you could (locally!) reuse color matrix from said other camera.
Otherwise, you could take a picture of color chart and make color matrix, but i'm not sure what's the darktable's story with accepting those.

**Comment by philippnormann** [comment]
@LebedevRI Thanks for the quick response! It shares most of its components with the RX100V, so I will try to reuse those matrices locally and submit a PR as soon as Adobe releases official support for this camera.

**Comment by philippnormann** [comment]
@LebedevRI Could you please have a look at the failed AppVeyor build. It seems to be an issue unrelated to this PR.
Judging from the logs, the failure seems to be related to this [announcement](https://www.msys2.org/news/#2020-06-29-new-packagers).

**Comment by LebedevRI** [comment]
@philippnormann thanks for the patches!

**Pull request merged**
