### PR TITLE
Panasonic DMC-FX150 support

### LINKED ISSUE #16554: Panasonic DMC-FX150
Panasonic DMC-FX150 - submitted two samples.
Thank you.

### PR DESCRIPTION
**Pull request by kmilos**
Resolves https://github.com/darktable-org/darktable/issues/16554

Missing the full set of aspect ratios though. @abpolly

### CODE REVIEW

**Comment by LebedevRI** [comment]
@kmilos please change your commit message template :)
It's quite unfortunate (read: wrong) that merging change here closes the issue in darktable repo.

**Comment by kmilos** [comment]
OK, I'll go back to "addresses" then...

**Comment by LebedevRI** [comment]
> OK, I'll go back to "addresses" then...

`Refs. <link>` is best. It still causes github to cross-reference, but does not auto-close them.
`Addresses` might or might not auto-close, i don't know.

**Comment by kmilos** [comment]
> `Addresses` might or might not auto-close, i don't know.

[It doesn't](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue), and is what I used for a while... But then at some point I thought you asked me to do auto-closing, but I must have misunderstood...

**Comment by LebedevRI** [comment]
> > `Addresses` might or might not auto-close, i don't know.
> 
> [It doesn't](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue), and is what I used for a while...

> But then at some point I thought you asked me to do auto-closing, but I must have misunderstood...

Hm, if i did, i was talking about auto-closing issues in *this* repo, not in darktable one.
Anyways, there's no problem, just a bit unfortunate. Thank you!

**Comment by kmilos** [comment]
> Hm, if i did, i was talking about auto-closing issues in _this_ repo, not in darktable one.

Got it, thanks.

**Comment by LebedevRI** [comment]
Looks good, but we *really* need @abpolly to contribute the samples...

**Comment by abpolly** [comment]
Uploaded two sets of three files - separate files for three aspect ratios.
Hope this time all is good
1.1-Panasonic-DMC-FX150-1.33-P1040340.RW2
1.2-Panasonic-DMC-FX150-1.50-P1040341.RW2
1.3-Panasonic-DMC-FX150-1.78-P1040342.RW2
2.1-Panasonic-DMC-FX150-1.33-P1040344.RW2
2.2-Panasonic-DMC-FX150-1.50-P1040345.RW2
2.3-Panasonic-DMC-FX150-1.78-P1040346.RW2

**Comment by LebedevRI** [comment]
@kmilos thank you!

**Pull request merged**
