### PR TITLE
Add Leica M10 Monochrom

### PR DESCRIPTION
**Pull request by kmilos**
Addresses https://github.com/darktable-org/darktable/issues/14034

### CODE REVIEW

**Comment by LebedevRI** [comment]
> Addresses https://github.com/darktable-org/darktable/issues/14034

Surely the monochromicity detection should not be affected by this diff?
Is the name matching really not case-insensitive?

**Comment by LebedevRI** [comment]
> Addresses https://github.com/darktable-org/darktable/issues/14034

Surely the monochromicity detection should not be affected by this diff?
Is the name matching really not case-insensitive?

**Comment by kmilos** [comment]
> Is the name matching really not case-insensitive?

It's not about the case, but sanitizing the maker/model pair, i.e. getting rid of "Camera AG" and the duplicate "Leica".

**Comment by kmilos** [comment]
> Is the name matching really not case-insensitive?

It's not about the case, but sanitizing the maker/model pair, i.e. getting rid of "Camera AG" and the duplicate "Leica".

**Comment by LebedevRI** [comment]
> > Is the name matching really not case-insensitive?
> 
> It's not about the case, but sanitizing the maker/model pair, i.e. getting rid of "Camera AG" and the duplicate "Leica".

Sure. But for DNG, presence of such a sanitization must not (at least should not) affect the outcome.

**Comment by kmilos** [comment]
It does not indeed, this PR is just for completeness since the samples were uploaded.

**Comment by LebedevRI** [comment]
Thanks!

**Pull request merged**
