### PR TITLE
Unbreak build on case-insensitive fs

### PR DESCRIPTION
**Pull request by LebedevRI**
For some reason `<cpuid.h>` first searches in current directory, just like it's `""` form, and after c2a68bb4124265eaf3b3dbac910b9cf32213943c, `Cpuid.h` is in the current directory of the compiler for `Cpuid.cpp`, which results in wrong file being included (global `<cpuid.h>` not being included)

https://github.com/darktable-org/rawspeed/pull/610#issuecomment-1903750793

### CODE REVIEW

**Comment by parafin** [comment]
It's probably due to -I. compiler flag used somewhere in build options.

**Comment by LebedevRI** [comment]
```
{
  "directory": "/home/lebedevri/rawspeed/build-Clang17-release",
  "command": "/usr/bin/clang++-17 -DNDEBUG -I/home/lebedevri/rawspeed/build-Clang17-release/src -I/home/lebedevri/rawspeed/src/librawspeed/common/.. -isystem /home/lebedevri/rawspeed/src/external  -Wall -Wextra -Weverything -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-c++20-extensions -Wno-padded -Wno-switch-enum -Wno-unused-parameter -Wno-sign-conversion -Wextra-semi -Wframe-larger-than=4096 -Wlarger-than=32768 -Werror -O3 -DNDEBUG -O3 -std=c++20 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden   -march=native -g3 -ggdb3 -fopenmp=libomp -fopenmp-version=50 -o src/librawspeed/common/CMakeFiles/rawspeed_common.dir/CpuFeatures.cpp.o -c /home/lebedevri/rawspeed/src/librawspeed/common/CpuFeatures.cpp",
  "file": "/home/lebedevri/rawspeed/src/librawspeed/common/CpuFeatures.cpp",
  "output": "src/librawspeed/common/CMakeFiles/rawspeed_common.dir/CpuFeatures.cpp.o"
},
```
I don't see `-I/home/lebedevri/rawspeed/src/librawspeed/common` in there,
it just searches [first] for `cpuid.h` in the same directory where the source file located.

**Comment by kmilos** [comment]
Confirming it's passing that build stage now on Windows, thanks. (Black level interface update is indeed next.)

**Comment by LebedevRI** [comment]
Something close to
```
Author: Roman Lebedev <lebedev.ri@gmail.com>
Date:   Mon Jan 22 16:13:09 2024 +0300

    tmp

diff --git a/src/imageio/imageio_rawspeed.cc b/src/imageio/imageio_rawspeed.cc
index c17e877cfc..80729eb158 100644
--- a/src/imageio/imageio_rawspeed.cc
+++ b/src/imageio/imageio_rawspeed.cc
@@ -208,16 +208,14 @@ dt_imageio_retval_t dt_imageio_open_rawspeed(dt_image_t *img,
     img->raw_black_level = r->blackLevel;
     img->raw_white_point = r->whitePoint;
 
-    if(!r->blackAreas.empty() || r->blackLevelSeparate[0] == -1
-       || r->blackLevelSeparate[1] == -1
-       || r->blackLevelSeparate[2] == -1
-       || r->blackLevelSeparate[3] == -1)
+    if(!r->blackAreas.empty() || !r->blackLevelSeparate)
     {
       r->calculateBlackAreas();
     }
 
+    const auto bl = *(r->blackLevelSeparate->getAsArray1DRef());
     for(uint8_t i = 0; i < 4; i++)
-      img->raw_black_level_separate[i] = r->blackLevelSeparate[i];
+      img->raw_black_level_separate[i] = bl(i);
 
     if(r->blackLevel == -1)
     {
@@ -398,7 +396,7 @@ dt_imageio_retval_t dt_imageio_open_rawspeed(dt_image_t *img,
                                         r->metadata.model.c_str(),
                                         r->metadata.mode.c_str());
 
-    if(cam && cam->supportStatus == Camera::SupportStatus::NoSamples)
+    if(cam && cam->supportStatus == Camera::SupportStatus::SupportedNoSamples)
       img->camera_missing_sample = TRUE;
   }
   catch(const std::exception &exc)
@@ -551,7 +549,7 @@ dt_imageio_retval_t dt_imageio_open_rawspeed_sraw(dt_image_t *img,
                                       r->metadata.model.c_str(),
                                       r->metadata.mode.c_str());
 
-  if(cam && cam->supportStatus == Camera::SupportStatus::NoSamples)
+  if(cam && cam->supportStatus == Camera::SupportStatus::SupportedNoSamples)
     img->camera_missing_sample = TRUE;
 
   return DT_IMAGEIO_OK;

```

**Pull request merged**
