### PR TITLE
Onwards to C++17 / OpenMP 4.5

### PR DESCRIPTION
**Pull request by LebedevRI**
Not really sure what this means for Apple XCode support.

### CODE REVIEW

**Comment by simonspa** [comment]
Most language features should be in Xcode/AppleClang 9.3 but many library features have only been added in version 10: https://en.cppreference.com/w/cpp/compiler_support#cpp17

**Comment by LebedevRI** [comment]
> Most language features should be in Xcode/AppleClang 9.3 but many library features have only been added in version 10: https://en.cppreference.com/w/cpp/compiler_support#cpp17

To me the "Apple Clang" columns read as "Yes", with no version specified..

Apple Clang/XCode 10 is already required, i think:
https://github.com/darktable-org/rawspeed/blob/ab3bf7290d5c6e086becdca4156be0254d8ee92a/cmake/compiler-versions.cmake#L17-L22

But that being said, as i've previously noted in https://github.com/darktable-org/rawspeed/issues/226#issuecomment-902792759

> @MStraeten @parafin sorry for necro-posting, but i'm revisiting this area of cmake, and i'm somewhat confused.
> This workarounds https://bugs.llvm.org/show_bug.cgi?id=35873, which was fixed in LLVM/Clang 7: https://godbolt.org/z/v9dcT9rK5
> But as per https://en.wikipedia.org/wiki/Xcode#Xcode_7.0_-_10.x_(since_Free_On-Device_Development)_2, the first XCode version based on LLVM 7 was `XCode 10.2` (aka `10.0.1 (clang-1001.0.46.3)`).
> 
> So how come
> 
> > (CMAKE_CXX_COMPILER_VERSION "11.0.0.11000033")
> 
> which i believe belongs to XCode 11.0, is still broken?
> 
> I guess my main question is: which is the first XCode version for which https://godbolt.org/z/v9dcT9rK5 is fixed?

**Comment by simonspa** [comment]
Phew, to be honest, I never fully understood the versioning of AppleClang and XCode.

The linked cppreference table notes "yes" for most, but "10.0.0" for some of the library features, hence my comment on that. They might still have not implemented.

I guess we'd have to add specific XCode versions to the CI and simply test if they work?

**Comment by LebedevRI** [comment]
> Phew, to be honest, I never fully understood the versioning of AppleClang and XCode.
> 
> The linked cppreference table notes "yes" for most, but "10.0.0" for some of the library features, hence my comment on that. They might still have not implemented.

> I guess we'd have to add specific XCode versions to the CI and simply test if they work?

That's what i'm currently trying to do..

**Comment by LebedevRI** [comment]
> > Phew, to be honest, I never fully understood the versioning of AppleClang and XCode.
> > The linked cppreference table notes "yes" for most, but "10.0.0" for some of the library features, hence my comment on that. They might still have not implemented.
> 
> > I guess we'd have to add specific XCode versions to the CI and simply test if they work?
> 
> That's what i'm currently trying to do..

Ok, that was surprisingly easy to do, #295.
I've added only the latest minor release of each available major release, hopefully that will be good-enough.

**Pull request merged**
