### PR TITLE
CI: update actions, streamline MSYS2 setup

### PR DESCRIPTION
**Pull request by kmilos**
[Security related changes:](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates)

* [GitHub actions are updated to their latest available version](https://github.com/darktable-org/rawspeed/network/dependencies)
  * w/ the exception of Codecov action (as breaking changes were mentioned), leaving that to someone more clued up...

Efficiency/environmental impact related changes:

* [In-progress CI jobs are cancelled if a new commit is pushed to an existing PR](https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-concurrency-to-cancel-any-in-progress-job-or-run)

* MSYS2 setup now installs the minimal set of needed packages instead of entire toolchain
  * also, [`pacboy` is used for arch/msystem independent package specification for install](https://github.com/msys2/setup-msys2#pacboy)

  Before : `Total Installed Size:  1603.82 MiB`

  After: `Total Installed Size:  116.40 MiB` + `Total Installed Size:  1141.37 MiB`

### CODE REVIEW

**Comment by LebedevRI** [comment]
This could use some more words in the description part i think.

**Comment by kmilos** [comment]
> This could use some more words in the description part i think.

Done.

**Comment by LebedevRI** [comment]
> * w/ the exception of Codecov action (as breaking changes were mentioned), leaving that to someone more clued up...

Where? https://github.com/codecov/codecov-action only mentions breaking changes when going from v1.

**Comment by kmilos** [comment]
> https://github.com/codecov/codecov-action only mentions breaking changes when going from v1.

True. Still,

> leaving that to someone more clued up...

**Comment by LebedevRI** [comment]
I'm not really sure about `concurrency` thing, the rest seems fine i guess.

**Comment by LebedevRI** [comment]
Thanks!

**Comment by kmilos** [comment]
> I'm not really sure about `concurrency` thing

I added the same to darktable and exiv2, works as advertised.

**Comment by LebedevRI** [comment]
E.g. i don't see why non-PR builds should be aborted.

**Comment by kmilos** [comment]
Yeah, not quite sure how to separate the "on push" and "on PR" references, but haven't seen any side effects yet with this setup...

**Pull request merged**
