### PR TITLE
Fujifilm X100F: add basic camera support

### PR DESCRIPTION
**Pull request by schenlap**
see darktable #11525

Dngmeta reads wrong cfa patter, manually fixed,
commressed images can not be loaded.

### CODE REVIEW

**Comment by LebedevRI** [comment]
@dtorop, @schenlap: thank you both!

**Comment by dtorop** [comment]
Should blackpoint be 1022 as in https://github.com/darktable-org/rawspeed/pull/92/files? This would be be in line with the `BlackLevel` in https://raw.pixls.us/getfile.php/1166/exiftool/DSCF0150.RAF.exiftool.txt, as @LebedevRI pointed out.

But it does seem the right route is to just teach RafDecoder to read `BlackLevel`directly from EXIF.

**Comment by dtorop** [comment]
I'm extra-puzzled, as if I look at the DNG created from raw.pixls.us `DSCF01050.RAF` via `exiftool -BlackLevel -s -G DSCF0150.dng` I see:

`[EXIF]          BlackLevel                      : 1024`

Which is as in this PR. But `exiftool -BlackLevel -s -G DSCF0150.RAF` reports, as https://raw.pixls.us/getfile.php/1166/exiftool/DSCF0150.RAF.exiftool.txt:

`[RAF]           BlackLevel                      : 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022 1022`

Obviously not that much difference between the two, but I'm curious as support for the BlackLevel tag in RawSpeed's `RafDecoder.cpp`, which would use the RAF, not DNG value.

**Comment by LebedevRI** [comment]
I see no 1024 in the RAF exif, only 36x 1022.
The RafDecoder will obiviously use the `[RAF] BlackLevel` values, though downsampled to 2x2 pattern.
Actually, i'm trying to teach it that right now...

**Comment by dtorop** [comment]
> Actually, i'm trying to teach it that right now...

Oh, that is great you're doing the RafDecoder work.

> I see no 1024 in the RAF exif, only 36x 1022.

That is why I am confused: I don't know why the DNG then uses 1024 in its BlackLevel tag, which is also the value now in `cameras.xml`. The disparity is also present for X-T1 and X-T2 but not X100S or X100T. I didn't check any other X-Trans cameras. it seems DNG just goes with 1024, regardless of BlackLevel in the RAF:

```
> exiftool -BlackLevel -s -G -H DSCF5086-Fujifilm_X-T1.*
======== DSCF5086-Fujifilm_X-T1.dng
[EXIF]          0xc61a BlackLevel                      : 1024
======== DSCF5086-Fujifilm_X-T1.RAF
[RAF]           0xf00a BlackLevel                      : 1023 1023 1023 1023 1023 1023 1023 1023 1023 1023 1023 1023 1023 1023 1023 1023 1023 1023 1023 1023 1023 1023 1023 1023 1023 1023 1023 1023 1023 1023 1023 1023 1023 1023 1023 1023
    2 image files read
> exiftool -BlackLevel -s -G -H 20170114_173532_TFW04723-Fujifilm_X-T2.*
======== 20170114_173532_TFW04723-Fujifilm_X-T2.dng
[EXIF]          0xc61a BlackLevel                      : 1024
======== 20170114_173532_TFW04723-Fujifilm_X-T2.RAF
[RAF]           0xf00a BlackLevel                      : 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020
    2 image files read
> exiftool -BlackLevel -s -G -H 20170114_173532_TFW04723-Fujifilm_X-T2.*
======== 20170114_173532_TFW04723-Fujifilm_X-T2.dng
[EXIF]          0xc61a BlackLevel                      : 1024
======== 20170114_173532_TFW04723-Fujifilm_X-T2.RAF
[RAF]           0xf00a BlackLevel                      : 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020 1020
    2 image files read
> exiftool -BlackLevel -s -G -H _DSF6020-x100s.*
======== _DSF6020-x100s.dng
[EXIF]          0xc61a BlackLevel                      : 1024
======== _DSF6020-x100s.RAF
[RAF]           0xf00a BlackLevel                      : 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024
    2 image files read
> exiftool -BlackLevel -s -G -H FUJIFILM-X100T-2.*
======== FUJIFILM-X100T-2.dng
[EXIF]          0xc61a BlackLevel                      : 1024
======== FUJIFILM-X100T-2.RAF
[RAF]           0xf00a BlackLevel                      : 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024 1024
    2 image files read
```

 All these cameras currently have `black` of 1024 in `cameras.xml`. Presumably the work you do on RafDecoder will override the 1024 with a slightly smaller value in the case of some cameras? It looks like rawprepare iop stores the black level, so it wouldn't alter extant images in dt, only newly imported ones?

This is all obviously incredibly minor, just about a difference of <= 4 in blackpoint!

**Comment by LebedevRI** [comment]
> Presumably the work you do on RafDecoder will override the 1024 with a slightly smaller value in the case of some cameras?

Good question. In case of black level, white level it would make sense to override whatever is in XML, but no, XML always overrides everything.
So for now it will just learn to read it, but then the data will be overridden.

> It looks like rawprepare iop stores the black level, so it wouldn't alter extant images in dt, only newly imported ones?

Eh, no, unfortunately :/
The params for default iop values are not stored in history stack.
This is a problem for all on-by-default modules - colorin, demosaic, temperature, rawprepare, ???

**Comment by dtorop** [comment]
>  So for now it will just learn to read it, but then the data will be overridden.
> ...
>  The params for default iop values are not stored in history stack.

Makes sense, and it seems harmless at least.

I had some working code which I just put up (https://github.com/darktable-org/rawspeed/commit/6d42c7f61dcb5bfee2d06efa14e28b6e169a40f5) which handles black level from EXIF via averaging it into `blackLevel`. I won't touch it more, though, and see what you come up with...

**Comment by LebedevRI** [comment]
Yes, pretty much, though you should average it down to 2x2, i.e. i think

| i\j | 0 | 1 | 2 | 3 | 4 | 5 |
|---|---|---|---|---|---|---|
| 0 | 0 | 1 | 0 | 1 | 0 | 1 |
| 1 | 2 | 3 | 2 | 3 | 2 | 3 |
| 2 | 0 | 1 | 0 | 1 | 0 | 1 |
| 3 | 2 | 3 | 2 | 3 | 2 | 3 |
| 4 | 0 | 1 | 0 | 1 | 0 | 1 |
| 5 | 2 | 3 | 2 | 3 | 2 | 3 |

**Comment by LebedevRI** [comment]
Ok, sep black level reading added.
Now that i actually think about it, it makes sense to [at least for now] always use it.

I'm not sure yet how to access that XTransLayout tag. It is in some kind of private metadata, address of which is located at offset `92`, see `parse_fuji()` of [`dcraw.c`](https://www.cybercom.net/~dcoffin/dcraw/dcraw.c)

Also, no clue where white level is hiding.

**Comment by LebedevRI** [comment]
Good news: i can read xtrans CFA pattern:
```diff
diff --git a/src/librawspeed/decoders/RafDecoder.cpp b/src/librawspeed/decoders/RafDecoder.cpp
index abd2c064..f0bee0b7 100644
--- a/src/librawspeed/decoders/RafDecoder.cpp
+++ b/src/librawspeed/decoders/RafDecoder.cpp
@@ -224,9 +225,39 @@ void RafDecoder::decodeMetaDataInternal(const CameraMetaData* meta) {
     }
   }
 
+  auto raw = mRootIFD->getIFDsWithTag((TiffTag)0x0131);
+  if(!raw.empty()) {
+    for(const auto& ifd : raw)
+    {
+      TiffEntry* entry = ifd->getEntry((TiffTag)0x0131);
+      if(entry->count != 36) continue;
+
+      mRaw->cfa.setSize({6, 6});
+
+      static const map<uchar8, CFAColor> byte2enum = {
+          {0, CFA_RED},     {1, CFA_GREEN},  {2, CFA_BLUE},
+      };
+
+      for (int y = 0; y < 6; y++) {
+        for (int x = 0; x < 6; x++) {
+          uint32 c1 = entry->getByte(x + 6 * y);
+          CFAColor c2 = CFA_UNKNOWN;
+
+          try {
+            c2 = byte2enum.at(c1);
+          } catch (std::out_of_range&) {
+            ThrowRDE("Unsupported CFA Color: %u", c1);
+          }
+
+          mRaw->cfa.setColorAt(iPoint2D(x, y), c2);
+        }
+      }
+    }
+  }
```
As expected, it also needs some shifting...
Edit: appears to be shifted by one both horizontally and vertically. If only the reasons would be obvious...

**Comment by dtorop** [comment]
Amazing! It'd be a happy day to lose all the CFA2 and ColorRow verbiage...

No idea here about why it needs shifting...

**Pull request merged**
