### PR TITLE
Updated 1Ds color matrix and sensor white

### PR DESCRIPTION
**Pull request by PeterWem**
Added white points/ISO for 1Ds and renewed its color matrix. Adobe DNG Converter 14.2 was used.
This PR solves #375

### CODE REVIEW

**Comment by LebedevRI** [comment]
Yep, incorrect black/white levels is a rather common problem.
We are really ought to stop hardcoding it, and reading it from EXIF instead.

**Comment by iiborg** [comment]
EXIF contains programmed black level, not the real one, especially for the cameras where the black level is calculated from the optical black, per row / per column.

**Comment by PeterWem** [comment]
> Yep, incorrect black/white levels is a rather common problem. We are really ought to stop hardcoding it, and reading it from EXIF instead.

Black level would be better from optical black, wouldn't it? About white point we don't have anything to measure, I assume?

Some black level tags for Canon, but Canon changes all the time https://www.dpreview.com/forums/thread/3789550?page=2

**Comment by kmilos** [comment]
There are many black level and white level tag locations for Canon cameras depending on model and makernote version:

https://exiftool.org/TagNames/Canon.html

**Comment by iiborg** [comment]
> Black level would be better from optical black, wouldn't it? 

Absolutely. That helps preventing pattern noise.

> About white point we don't have anything to measure, I assume?

White point is calculated from raw data if raw data is clipped.

**Comment by LebedevRI** [comment]
@PeterWem thank you!

**Pull request merged**
