### PR TITLE
Sony ILCE-7CM2 support

### PR DESCRIPTION
**Pull request by kmilos**
Confirmed as a copy of 7M4 by ADC 16.0

### CODE REVIEW

**Comment by LebedevRI** [comment]
There are zero samples for `ILCE-7CR` on RPU.
Can you please split that into a separate PR?

**Comment by kmilos** [comment]
> Can you please split that into a separate PR?

Done. I'll push the other one later.

**Comment by kmilos** [comment]
[The APS-C crop is not ideal](https://github.com/darktable-org/rawspeed/issues/520#issuecomment-1757101416), but I suggest we go w/ the FF value just as for the 7M4 for now.

**Comment by kmilos** [comment]
@LebedevRI Can we merge this as is please so I can push a 7CR one? Any extra crop related codebase work will obviously have to come separately and handle 7M4 and 7CM2 at the same time...

**Comment by LebedevRI** [comment]
> @LebedevRI Can we merge this as is please so I can push a 7CR one? Any extra crop related codebase work will obviously have to come separately and handle 7M4 and 7CM2 at the same time...

Sorry, i meant to merge this right after the PR was split. I'll merge today.

**Comment by LebedevRI** [comment]
@kmilos thank you.

**Pull request merged**
