### PR TITLE
cmake: add missing OpenMP-related commands

### PR DESCRIPTION
**Pull request by parafin**
fixes native support for OpenMP on macOS with cmake 3.16

### CODE REVIEW

**Comment by LebedevRI** [comment]
While there, can you also drop https://github.com/darktable-org/rawspeed/pull/210/files#diff-3b80067364ac3a144f97bef846683a7cR46-R55 ?

**Comment by parafin** [comment]
done, unless you want to get rid of RawSpeed::OpenMP_CXX too.

I have a question - will this PR be included in darktable 3.0? I understand darktable doesn't always track latest commit in develop rawspeed branch

**Comment by LebedevRI** [comment]
Thanks, will merge tomorrow.

> done, unless you want to get rid of RawSpeed::OpenMP_CXX too.

No, that should stay.

> I have a question - will this PR be included in darktable 3.0? I understand darktable doesn't always track latest commit in develop rawspeed branch

I'm not sure yet when i will be comfortable updating darktable's submodule version,
there's some changes that need to bake-in (fuzz e.g.), and have more outstanding changes.

**Comment by LebedevRI** [comment]
> > I have a question - will this PR be included in darktable 3.0? I understand darktable doesn't always track latest commit in develop rawspeed branch
> 
> I'm not sure yet when i will be comfortable updating darktable's submodule version,
> there's some changes that need to bake-in (fuzz e.g.), and have more outstanding changes.

And apparently it will be.

While there, i finally created "stable" branch which will be tracked by darktable rawspeed submodule
instead of develop branch, with subtext that since the "stable" rawspeed fixpoint is already
what darktable rawspeed submodule was tracking, we might as well do that in rawspeed itself.

**Pull request merged**
