### PR TITLE
Fujifilm X-T30 II support

### PR DESCRIPTION
**Pull request by kmilos**
Addresses https://github.com/darktable-org/darktable/issues/10755

@LebedevRI ~~This is a stub only, I have not verified the CFA pattern nor the crop.~~

### CODE REVIEW

**Comment by kmilos** [comment]
Btw, something funny going on here - I seem to get swapped channels between compressed vs uncompressed modes, and playing w/ crop or channel order doesn't seem to fix it...

**Comment by cytrinox** [comment]
@kmilos Some Fujifilm models has different CFA for compressed mode like X-T20 which is already handled here with two definitions: https://github.com/darktable-org/rawspeed/blob/586d1492492d9df8a7683401f3017c54a770ffce/data/cameras.xml#L15648
**But I can not confirm this for X-T30 II.** The pattern is equal for all three raw samples (lossy, lossless, uncompressed).

Caution: The X-Trans-Layout reported by exiftool is always in wrong order. For the *right* pattern starting at (0, 0) you just have to read the pattern backwards (letter by letter).

````
exiftool -XTransLayout *
======== X-T30-II-14-bits-lossless.RAF
X-Trans Layout                  : GRBGBR BGGRGG RGGBGG GBRGRB RGGBGG BGGRGG
======== X-T30-II-14-bits-lossy.RAF
X-Trans Layout                  : GRBGBR BGGRGG RGGBGG GBRGRB RGGBGG BGGRGG
======== X-T30-II-14-bits-uncompressed.RAF
X-Trans Layout                  : GRBGBR BGGRGG RGGBGG GBRGRB RGGBGG BGGRGG
    3 image files read
````

I've the following defintion in dnglab for X-T30 II:
````
make = "FUJIFILM"
model = "X-T30 II"
clean_make = "Fujifilm"
clean_model = "X-T30 II"
blackpoint = 1024
whitepoint = 16383
color_pattern = "GGRGGBGGBGGRBRGRBGGGBGGRGGRGGBRBGBRG"
active_area = [0, 5, 132, 1] # L, T, R, B
````

So after dng conversion, all patterns are still the same but rotated by 5 rows:

````
exiftool -CFAPattern -ActiveArea /tmp/dngout/*
======== /tmp/dngout/X-T30-II-14-bits-lossless.dng
CFA Pattern                     : [Red,Blue,Green,Blue,Red,Green][Green,Green,Red,Green,Green,Blue][Green,Green,Blue,Green,Green,Red][Blue,Red,Green,Red,Blue,Green][Green,Green,Blue,Green,Green,Red][Green,Green,Red,Green,Green,Blue]
Active Area                     : 5 0 4181 6252
======== /tmp/dngout/X-T30-II-14-bits-lossy.dng
CFA Pattern                     : [Red,Blue,Green,Blue,Red,Green][Green,Green,Red,Green,Green,Blue][Green,Green,Blue,Green,Green,Red][Blue,Red,Green,Red,Blue,Green][Green,Green,Blue,Green,Green,Red][Green,Green,Red,Green,Green,Blue]
Active Area                     : 5 0 4181 6252
======== /tmp/dngout/X-T30-II-14-bits-uncompressed.dng
CFA Pattern                     : [Red,Blue,Green,Blue,Red,Green][Green,Green,Red,Green,Green,Blue][Green,Green,Blue,Green,Green,Red][Blue,Red,Green,Red,Blue,Green][Green,Green,Blue,Green,Green,Red][Green,Green,Red,Green,Green,Blue]
Active Area                     : 5 0 4181 6252
    3 image files read
````
There is no different decoder required for X-T30 II and I would tend to say if you just define the camera in cameras.xml with this pattern: "GGRGGBGGBGGRBRGRBGGGBGGRGGRGGBRBGBRG" it should work out of the box.

**Comment by kmilos** [comment]
As I wrote earlier, I think I already tried playing / the CFA order to no success... I'll check again when I get a chance.

**Comment by kmilos** [comment]
@cytrinox Indeed, it is "GGRGGBGGBGGRBRGRBGGGBGGRGGRGGBRBGBRG" while I only tried vertical shifting of the "BGGRGGGRBGBRBGGRGGGBRGRBRGGBGG" the Adobe DNG Converter gave me... Thanks!

Anyhow, I added the crop as well, so this should also be good to go. (Apart from the lossy compressed mode like other Fujifilms of course.)

**Comment by LebedevRI** [comment]
@kmilos thank you!

**Pull request merged**
