### PR TITLE
Add Sony ZV-1M2 placeholder

### PR DESCRIPTION
**Pull request by kmilos**

### CODE REVIEW

**Comment by kmilos** [comment]
Duh, already had https://github.com/darktable-org/rawspeed/pull/488

**Comment by LebedevRI** [comment]
As i've explained before, i'd rather merge this kind of thing than have https://github.com/darktable-org/rawspeed/pull/488 leave forever open.

**Comment by kmilos** [comment]
Go for it.

**Comment by LebedevRI** [comment]
PR's can't be reopened once the branch has been deleted.

**Comment by kmilos** [comment]
Sorry 😔

**Comment by LebedevRI** [comment]
@kmilos thank you!

**Pull request merged**
