### PR TITLE
Some changes...

### PR DESCRIPTION
**Pull request by LebedevRI**

### CODE REVIEW

**Review by axxel — COMMENTED** [review]
I have mostly used the code with multi-threading inside the library disabled (i.e. NO_PTHREAD defined). It should work either way.

**Comment by LebedevRI** [comment]
@axxel is `rstest` supposed to use some modified `cameras.xml`, or the vanilla-one?

**Comment by axxel** [comment]
I never used anything other than the upstream version. I simply symlinked/copied the file into the wc, so the tool can easily find it.

**Comment by LebedevRI** [comment]
Ah, good. Now it should just work, by hardcoding the build-time full path to `cameras.xml` in git checkout.

**Pull request merged**
