### PR TITLE
Fujifilm GFX100 II support

### PR DESCRIPTION
**Pull request by kmilos**
Using ADC 16.0

Currently uncompressed and lossless compressed only, as with other Fujifilm cameras.

https://github.com/darktable-org/darktable/issues/16130

### CODE REVIEW

**Comment by kmilos** [comment]
@LebedevRI [I have a few open PRs](https://github.com/darktable-org/rawspeed/pulls?q=is%3Aopen+author%3Akmilos+sort%3Aupdated-desc) where codecov seems to be running periodically and updating the status, you have any idea what might be triggering it?

**Comment by LebedevRI** [comment]
> @LebedevRI [I have a few open PRs](https://github.com/darktable-org/rawspeed/pulls?q=is%3Aopen+author%3Akmilos+sort%3Aupdated-desc) where codecov seems to be running periodically and updating the status, you have any idea what might be triggering it?

I don't have an answer but i could guess that it either reacted to the new changes in the `develop` branch,
or some github CI job completed/timeouted and it updated the status accordingly. Does not seem erroneous to me.

**Comment by kmilos** [comment]
Updated the crop slightly, should be good to go now - seems to be working ok on those RPU samples (except the lossy ones of course).

P.S. I think you can remove the 32-bit MSYS environments from CI, [they're being phased out](https://www.msys2.org/news/#2023-12-13-starting-to-drop-some-32-bit-packages).

**Comment by LebedevRI** [comment]
> P.S. I think you can remove the 32-bit MSYS environments from CI, [they're being phased out](https://www.msys2.org/news/#2023-12-13-starting-to-drop-some-32-bit-packages).

Right. At this point i'm not really sure if this library _needs_ to support 32-bit environment
(in general, not just for some specific OS), so while i've tried to keep 32-bit CI working
(openSUSE_Tumbleweed @ i586 is essentially dead too),
i'm not sure how much effort is worth spending on that.

But once said CI can not be used anymore, 32-bit env would also be blocked via a cmake check like compiler versions.

**Comment by LebedevRI** [comment]
I can not verify crop at all here, samples are really bad.

**Comment by LebedevRI** [comment]
@kmilos thank you!

**Comment by kmilos** [comment]
Pretty sure it's meant to be the same as Mark I...

**Pull request merged**
