### PR TITLE
Add DC-GX7MK3 alias & remove spaces

### PR DESCRIPTION
**Pull request by ponkotuy**
In Japan, the GX9 is called GX7MK3.

### CODE REVIEW

**Comment by LebedevRI** [comment]
Thanks.
It seems like a sample from that camera is missing on https://raw.pixls.us,
it would be good to have it there.

**Comment by ponkotuy** [comment]
I've uploaded it to https://raw.pixls.us, is there anything else I need to do?

**Comment by LebedevRI** [comment]
> I've uploaded it to https://raw.pixls.us

Eh.
As it is stated on the first page there, 
it's best to not have people in those images.

>is there anything else I need to do?

No.

**Comment by ponkotuy** [comment]
I've uploaded a photo without people in it.

**Pull request merged**
