### PR TITLE
Add k-1 II support.

### PR DESCRIPTION
**Pull request by mazhe**
Hi, I juste received my Pentax K-1 II and am working on darktable support.

Since the sensor is strictly the same as the K-1 mark I, I don't think there should be any change in values? I've sent a first sample to raw.pixls.us

### CODE REVIEW

**Comment by LebedevRI** [comment]
Yes, i have seen the pr.
Sorry, did not to this yet..

**Comment by mazhe** [comment]
Hello, any progress regarding this request? Then I can open one for the rest of the support in darktable...

Thanks!

**Comment by LebedevRI** [comment]
Uhm, right, sorry.
With some tuning, merged.

Please contribute the full sample set for that camera - i was so sure there was coverage already - to the RPU - just two samples - DNG and PEF.
No need for pixel shift, or crops.

**Comment by mazhe** [comment]
Thanks, I already tried to upload some samples (as I did with the first k-1), but they never showed up... Is there some size limit or something like that? I'll try again this weekend.

**Comment by LebedevRI** [comment]
There is a pre-review. I don't think i remember seeing any dng+pef samples for `k-1 II`.

**Pull request merged**
